// Biblioteca de detectores del motor de diagnóstico de Cometia.
// Generada con verificación de honestidad (sin cifras inventadas, lenguaje de negocio).
// Cada detector: framing; la LÓGICA de cuándo se dispara vive en engine.js.
export const DETECTORES = {
  "lcp-alto": {
    "id": "lcp-alto",
    "categoria": "Velocidad",
    "titulo": "Tu contenido principal tarda demasiado en aparecer",
    "queSignifica": "Cuando alguien abre tu web, el elemento más grande de la pantalla (una imagen de cabecera, el titular o el banner principal) tarda más de lo recomendable en mostrarse. Durante ese rato el visitante ve una página a medio cargar.",
    "impacto": "Puede hacer que parte de las visitas se marchen antes de ver tu oferta, sobre todo desde el móvil. Google también tiene en cuenta esta rapidez, así que es una señal que conviene mejorar.",
    "causa": "Suele deberse a una imagen principal muy pesada, a un servidor que responde lento o a archivos de programación que se cargan antes que el contenido que se ve.",
    "recomendacion": "Aligerar la imagen o el bloque principal, cargarlo con prioridad y reducir lo que se ejecuta antes de que aparezca. Conviene identificar qué elemento concreto es el que tarda.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "respuesta-servidor-lenta": {
    "id": "respuesta-servidor-lenta",
    "categoria": "Velocidad",
    "titulo": "Tu servidor tarda en responder a cada visita",
    "queSignifica": "Antes de que el navegador pueda mostrar nada, tu servidor tiene que preparar y enviar la página. Ese primer paso está tardando más de lo deseable, así que todo lo demás arranca con retraso.",
    "impacto": "Puede penalizar la velocidad de toda la web, porque este retraso inicial se suma a cualquier otra carga. Es una señal que conviene revisar, ya que afecta a cada visita desde el primer segundo.",
    "causa": "Habitual en alojamientos compartidos muy económicos, webs con muchos plugins, bases de datos sin optimizar o sin una capa de caché en el servidor.",
    "recomendacion": "Revisar el plan de alojamiento, activar caché de página en el servidor y optimizar la base de datos. En algunos casos compensa cambiar a un hosting más rápido.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "javascript-sobrante": {
    "id": "javascript-sobrante",
    "categoria": "Velocidad",
    "titulo": "Tu web carga programación que no llega a usar",
    "queSignifica": "Se descarga código de funcionamiento que en esa página no se utiliza. El navegador tiene que traerlo y procesarlo igualmente, lo que consume tiempo para nada.",
    "impacto": "Puede ralentizar la carga y hacer que la web tarde más en responder al primer toque o clic, sobre todo en móviles más modestos. Es un lastre que conviene reducir.",
    "causa": "Frecuente cuando se acumulan plugins o plantillas que cargan sus archivos en todas las páginas, aunque solo hagan falta en una.",
    "recomendacion": "Cargar cada archivo solo donde se necesita, eliminar plugins que no se usan y dividir el código para que solo baje lo imprescindible en cada página.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "css-sobrante": {
    "id": "css-sobrante",
    "categoria": "Velocidad",
    "titulo": "Tu web carga estilos visuales que no utiliza",
    "queSignifica": "Además del contenido, se descargan reglas de diseño (colores, tamaños, márgenes) que en esa página no se aplican. El navegador las procesa aunque no sirvan.",
    "impacto": "Puede retrasar el momento en que la página se ve terminada y bien maquetada. No suele ser el problema más grave, pero es peso extra que conviene quitar.",
    "causa": "Habitual con plantillas y maquetadores visuales que incluyen estilos para muchísimas opciones, se usen o no en tu web.",
    "recomendacion": "Depurar los estilos que no se usan y cargar primero solo lo necesario para lo que se ve al abrir la página.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "recursos-bloqueantes": {
    "id": "recursos-bloqueantes",
    "categoria": "Velocidad",
    "titulo": "Algunos archivos frenan la aparición de tu página",
    "queSignifica": "Ciertos archivos de estilo y de programación se cargan antes que el contenido y obligan al navegador a esperar. Hasta que no terminan, el visitante no ve la página.",
    "impacto": "Puede hacer que la web se quede en blanco unos instantes de más al abrirla, lo que empeora la primera impresión. Es una señal que conviene corregir.",
    "causa": "Suele pasar cuando esos archivos se colocan en la parte alta de la página sin indicar que pueden esperar a más adelante.",
    "recomendacion": "Marcar esos archivos para que no bloqueen, cargarlos más tarde o incluir directamente en la página lo mínimo necesario para pintar lo primero que se ve.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "imagenes-pesadas": {
    "id": "imagenes-pesadas",
    "categoria": "Velocidad",
    "titulo": "Tienes imágenes que pesan más de lo necesario",
    "queSignifica": "Algunas fotos o gráficos de tu web ocupan mucho más de lo que deberían. El visitante tiene que descargar todo ese peso, y eso alarga la carga.",
    "impacto": "Puede hacer que la web vaya lenta, sobre todo con datos móviles o conexiones flojas, y consume datos del visitante. Es de lo que más suele frenar una web, así que conviene solucionarlo.",
    "causa": "Muy habitual al subir fotos directamente de la cámara o el móvil, sin comprimirlas ni ajustarles el tamaño antes.",
    "recomendacion": "Comprimir las imágenes y ajustarlas al tamaño real en que se muestran antes de subirlas. Hay herramientas sencillas para hacerlo sin perder calidad apreciable.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "imagenes-formato-antiguo": {
    "id": "imagenes-formato-antiguo",
    "categoria": "Velocidad",
    "titulo": "Tus imágenes usan un formato más pesado del disponible",
    "queSignifica": "Las fotos están guardadas en formatos antiguos (como JPG o PNG) cuando existen otros más modernos que pesan bastante menos con la misma calidad.",
    "impacto": "Al pesar más de lo necesario, pueden ralentizar la carga de las páginas con muchas imágenes. Es una mejora clara, aunque no siempre urgente.",
    "causa": "Normal, porque la mayoría de cámaras, móviles y bancos de imágenes siguen entregando los formatos de siempre.",
    "recomendacion": "Convertir las imágenes a formatos modernos (WebP o AVIF), algo que muchos gestores de web hacen de forma automática con un ajuste o un complemento.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "imagenes-sin-dimensionar": {
    "id": "imagenes-sin-dimensionar",
    "categoria": "Velocidad",
    "titulo": "Tus imágenes no reservan su sitio mientras cargan",
    "queSignifica": "Las imágenes no indican de antemano el espacio que van a ocupar. Mientras cargan no reservan hueco, y al aparecer empujan al resto del contenido.",
    "impacto": "Puede provocar saltos molestos en la página: el visitante va a pulsar algo y el contenido se mueve. Da una sensación de web poco pulida que conviene evitar.",
    "causa": "Suele ocurrir cuando en el código de la imagen no se indican su ancho y su alto, o no se adapta bien a cada tamaño de pantalla.",
    "recomendacion": "Indicar las dimensiones de cada imagen y servir versiones adaptadas a móvil y a ordenador para que reserven su espacio desde el principio.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "sin-compresion-servidor": {
    "id": "sin-compresion-servidor",
    "categoria": "Velocidad",
    "titulo": "Tu servidor envía los archivos sin comprimir",
    "queSignifica": "Los archivos de texto de la web (la página, los estilos, la programación) se pueden enviar comprimidos para que ocupen mucho menos por el camino. Tu servidor los está mandando sin comprimir.",
    "impacto": "Supone transferir más datos de los necesarios en cada visita, lo que puede ralentizar la carga sin motivo. Es de las mejoras más fáciles de aplicar.",
    "causa": "Suele deberse a que el servidor no tiene activada la compresión, algo que a veces viene desactivado por defecto.",
    "recomendacion": "Activar la compresión (Gzip o Brotli) en el servidor. Es un ajuste puntual, con efecto inmediato y sin riesgo para el contenido.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "sin-cache": {
    "id": "sin-cache",
    "categoria": "Velocidad",
    "titulo": "Los visitantes que repiten vuelven a descargarlo todo",
    "queSignifica": "La web no le dice al navegador que guarde archivos que casi no cambian (como el logo o los estilos). Así, quien vuelve a entrar tiene que descargarlos otra vez desde cero.",
    "impacto": "Puede hacer que las visitas repetidas y la navegación entre páginas sean más lentas de lo necesario. Es una mejora sencilla que conviene aprovechar.",
    "causa": "Habitual cuando el servidor no está configurado para indicar durante cuánto tiempo se pueden reutilizar los archivos.",
    "recomendacion": "Configurar el almacenamiento en caché del navegador para los archivos que rara vez cambian, indicando un tiempo de reutilización adecuado.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "muchos-scripts-terceros": {
    "id": "muchos-scripts-terceros",
    "categoria": "Velocidad",
    "titulo": "Tu web depende de muchos servicios externos",
    "queSignifica": "La página carga muchos elementos de otras empresas (chats, píxeles de publicidad, analíticas, botones sociales). Cada uno tira de un servidor ajeno que tú no controlas.",
    "impacto": "Puede ralentizar la web y hacer que su velocidad dependa de servidores de terceros. Además, algunos recogen datos del visitante, algo que conviene tener controlado. Es una señal a revisar.",
    "causa": "Se acumulan con el tiempo al ir añadiendo herramientas de marketing, medición y soporte sin retirar las que ya no se usan.",
    "recomendacion": "Revisar la lista y quedarse solo con lo que aporta, cargar lo que se pueda de forma diferida y valorar alternativas más ligeras.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "cls-inestable": {
    "id": "cls-inestable",
    "categoria": "Velocidad",
    "titulo": "El contenido salta y se recoloca mientras carga",
    "queSignifica": "Al cargar la página, los elementos se mueven de sitio: aparece una imagen, entra un anuncio o cambia una tipografía y todo lo demás se desplaza. La página no se queda quieta hasta pasado un rato.",
    "impacto": "Puede provocar clics equivocados y una sensación de web inestable o poco fiable. Google también valora esta estabilidad, así que es una señal que conviene corregir.",
    "causa": "Suele venir de imágenes o anuncios sin espacio reservado, tipografías que cargan tarde o contenidos que se insertan por encima de lo ya visible.",
    "recomendacion": "Reservar el espacio de imágenes, anuncios y bloques dinámicos desde el principio para que nada empuje al resto una vez cargado.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "fuentes-tardias": {
    "id": "fuentes-tardias",
    "categoria": "Velocidad",
    "titulo": "Los textos tardan en verse por culpa de las tipografías",
    "queSignifica": "Tu web usa tipografías que se descargan aparte. Mientras llegan, el texto puede quedar invisible o cambiar de golpe de aspecto cuando terminan de cargar.",
    "impacto": "Puede hacer que el visitante no vea el texto durante un instante o note un salto en las letras. Es un detalle que resta pulido y conviene ajustar.",
    "causa": "Ocurre cuando las tipografías no indican qué mostrar mientras cargan, o se traen desde servidores externos que tardan.",
    "recomendacion": "Indicar a la web que muestre un texto de reserva mientras llega la tipografía y cargar las fuentes desde tu propio servidor con prioridad.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "javascript-antiguo": {
    "id": "javascript-antiguo",
    "categoria": "Velocidad",
    "titulo": "Tu web arrastra programación pensada para navegadores viejos",
    "queSignifica": "Parte del código incluye añadidos para funcionar en navegadores muy antiguos que hoy casi nadie usa. Ese extra se descarga y se procesa en todos los dispositivos, también en los modernos.",
    "impacto": "Puede sumar peso y trabajo innecesarios que ralentizan un poco la web sin dar nada a cambio a la mayoría de visitantes. Es una optimización recomendable.",
    "causa": "Habitual con plantillas o librerías antiguas, o con configuraciones que generan código compatible con navegadores ya en desuso.",
    "recomendacion": "Actualizar las librerías y ajustar la generación del código para los navegadores actuales, eliminando los parches que ya no hacen falta.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "sin-https": {
    "id": "sin-https",
    "categoria": "Seguridad",
    "titulo": "Tu web no muestra el candado de conexión segura",
    "queSignifica": "La web se sirve sin conexión cifrada, así que la información entre el visitante y tu página viaja sin proteger. El navegador puede llegar a avisar de que el sitio 'no es seguro'.",
    "impacto": "Puede generar desconfianza inmediata en quien te visita y hacer que abandone, sobre todo en formularios o pagos. Los navegadores lo marcan de forma bien visible, así que es de lo más urgente a resolver.",
    "causa": "Suele deberse a que no hay certificado de seguridad instalado o a que la web sigue cargándose por la dirección antigua sin cifrar.",
    "recomendacion": "Instalar un certificado de seguridad (SSL) y forzar que toda la web se abra siempre por la versión cifrada. Muchos alojamientos lo ofrecen sin coste.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "critico",
    "confianza": "medido"
  },
  "errores-consola": {
    "id": "errores-consola",
    "categoria": "Velocidad",
    "titulo": "Tu web arroja errores internos al cargarse",
    "queSignifica": "Al abrir la página se producen errores en su funcionamiento interno que el visitante no ve directamente, pero que indican que algo no está trabajando como debería.",
    "impacto": "Pueden estar detrás de funciones que fallan (un formulario, un menú, un botón) o de una carga menos fluida. Es una señal de salud técnica que conviene revisar.",
    "causa": "Suelen venir de archivos de programación que chocan entre sí, plugins desactualizados, archivos que no cargan o servicios externos caídos.",
    "recomendacion": "Revisar los errores uno a uno, actualizar o sustituir lo que los provoca y comprobar que las funciones importantes vuelven a ir bien.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "librerias-vulnerables": {
    "id": "librerias-vulnerables",
    "categoria": "Seguridad",
    "titulo": "Tu web usa componentes con fallos de seguridad conocidos",
    "queSignifica": "Algunas de las piezas de software que hacen funcionar tu web están desactualizadas y tienen fallos de seguridad ya conocidos y documentados públicamente.",
    "impacto": "Puede abrir la puerta a que alguien aproveche esos fallos para colar publicidad, robar datos o dejar la web fuera de servicio. Es un riesgo de seguridad que conviene atender cuanto antes.",
    "causa": "Habitual cuando el gestor de contenidos, las plantillas o los plugins no se actualizan con regularidad y quedan versiones antiguas.",
    "recomendacion": "Actualizar los componentes afectados a una versión sin fallos conocidos y establecer una rutina de actualizaciones y copias de seguridad periódicas.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "critico",
    "confianza": "medido"
  },
  "sin-title": {
    "id": "sin-title",
    "categoria": "SEO",
    "titulo": "Tu página no tiene título para Google",
    "queSignifica": "El título es el texto azul que la gente ve en los resultados de Google y en la pestaña del navegador. Ahora mismo tu página no tiene uno definido, así que Google se lo inventa a partir de lo que encuentre.",
    "impacto": "Sin un título propio, Google decide por ti qué texto mostrar y suele quedar poco claro. Es una señal que conviene corregir cuanto antes, porque el título es lo primero que ve alguien que te busca.",
    "causa": "Suele pasar cuando la plantilla de la web no genera títulos o no hay un plugin de SEO configurado.",
    "recomendacion": "Ponle a cada página un título único de unos 50-60 caracteres que incluya lo que ofreces y, si tiene sentido, tu ciudad. Por ejemplo: 'Fontanería urgente en Albacete | Nombre de tu empresa'.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "title-corto": {
    "id": "title-corto",
    "categoria": "SEO",
    "titulo": "El título de tu página se queda demasiado corto",
    "queSignifica": "El título que aparece en Google existe, pero es tan breve que desaprovecha espacio. Con tan pocas palabras cuesta explicar qué ofreces y por qué elegirte.",
    "impacto": "Un título muy corto da poca información a quien busca y a Google. Puede hacer que tu resultado llame menos la atención que el de la competencia.",
    "causa": "Normalmente es solo el nombre de la empresa o una palabra suelta, sin describir el servicio.",
    "recomendacion": "Amplíalo hasta unos 50-60 caracteres añadiendo lo que haces y dónde. En vez de 'Mi Empresa', algo como 'Reformas de baños en Valencia | Mi Empresa'.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "title-largo": {
    "id": "title-largo",
    "categoria": "SEO",
    "titulo": "El título de tu página es tan largo que Google lo corta",
    "queSignifica": "Tu título tiene tantas palabras que Google no lo muestra entero en los resultados: lo corta con puntos suspensivos y la parte final se pierde.",
    "impacto": "Si la parte importante queda cortada, quien busca no llega a leerla. Es una señal que conviene ajustar para que tu mensaje se vea completo.",
    "causa": "Suele ocurrir al meter demasiadas palabras clave o el nombre completo de la empresa junto con eslóganes.",
    "recomendacion": "Recórtalo a unos 55-60 caracteres y deja lo más importante al principio, que es lo que siempre se ve.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "sin-meta-description": {
    "id": "sin-meta-description",
    "categoria": "SEO",
    "titulo": "Falta el pequeño resumen que aparece bajo tu página en Google",
    "queSignifica": "Debajo del título, en los resultados de Google, hay un par de líneas que resumen de qué va la página. No las has definido, así que Google coge un trozo cualquiera de tu texto.",
    "impacto": "Cuando ese resumen lo elige Google al azar, puede quedar confuso o poco atractivo. Escribirlo tú es una oportunidad para convencer a quien duda entre entrar o no.",
    "causa": "Es habitual cuando no se ha rellenado ese campo en el gestor de la web o falta un plugin de SEO.",
    "recomendacion": "Escribe para cada página un resumen de unos 150 caracteres que diga qué ofreces e invite a entrar, con una llamada clara como 'Pide presupuesto sin compromiso'.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "meta-description-corta": {
    "id": "meta-description-corta",
    "categoria": "SEO",
    "titulo": "El resumen que sale bajo tu página en Google se queda escaso",
    "queSignifica": "Ese resumen de un par de líneas que aparece bajo el título existe, pero es muy corto y deja espacio sin aprovechar para explicar lo que ofreces.",
    "impacto": "Con pocas palabras cuesta despertar interés. Aprovechar ese espacio puede ayudar a que más gente decida entrar en tu web.",
    "causa": "Suele ser una frase suelta que se quedó a medias al configurar la página.",
    "recomendacion": "Amplíalo hasta unos 140-155 caracteres describiendo el servicio y añadiendo una invitación a actuar.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "meta-description-larga": {
    "id": "meta-description-larga",
    "categoria": "SEO",
    "titulo": "El resumen bajo tu página en Google es tan largo que se corta",
    "queSignifica": "El texto que resume tu página en los resultados es demasiado largo y Google lo recorta, dejando la frase a medias.",
    "impacto": "Si la frase se corta, el mensaje puede quedar incompleto justo donde ibas a convencer. Conviene ajustarlo para que se lea entero.",
    "causa": "Ocurre al intentar meter demasiada información en ese pequeño espacio.",
    "recomendacion": "Recórtalo a unos 150 caracteres y coloca lo más importante al principio.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "sin-h1": {
    "id": "sin-h1",
    "categoria": "SEO",
    "titulo": "A tu página le falta el titular principal",
    "queSignifica": "El titular principal es el encabezado grande que resume de qué va la página, tanto para quien la lee como para Google. Tu página no tiene uno claro.",
    "impacto": "Sin un titular principal, cuesta más entender de un vistazo de qué trata la página. Es una señal que conviene corregir para dejar claro el tema desde el primer momento.",
    "causa": "A veces la plantilla usa el logo o una imagen como encabezado en lugar de un titular de texto.",
    "recomendacion": "Asegúrate de que cada página tenga un único titular principal en texto que resuma su contenido, por ejemplo 'Carpintería a medida en Sevilla'.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "varios-h1": {
    "id": "varios-h1",
    "categoria": "SEO",
    "titulo": "Tu página tiene varios titulares principales compitiendo entre sí",
    "queSignifica": "Lo habitual es que haya un solo titular principal por página, para dejar claro el tema de un vistazo. En la tuya hay varios marcados como principales, y eso resta claridad sobre cuál es el que manda.",
    "impacto": "No es una penalización, pero tener varios titulares principales puede difuminar de qué trata realmente la página para quien la lee y para Google. Dejar uno solo hace el mensaje más nítido.",
    "causa": "Suele venir de la plantilla o de bloques de diseño que marcan como titular principal elementos que en realidad no lo son.",
    "recomendacion": "Deja un único titular principal por página y convierte el resto en subtítulos.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "sin-canonical": {
    "id": "sin-canonical",
    "categoria": "SEO",
    "titulo": "A tu página le falta la señal que evita contenido duplicado",
    "queSignifica": "Es una etiqueta invisible que le dice a Google cuál es la dirección 'oficial' de esta página. Sin ella, si la misma página es accesible por varias direcciones, Google puede confundirse sobre cuál mostrar.",
    "impacto": "Cuando Google encuentra el mismo contenido en varias direcciones, puede repartir su valor entre ellas o elegir la que no quieres. Es una señal técnica que conviene dejar bien definida.",
    "causa": "Es frecuente en tiendas online y webs con filtros o parámetros en la dirección; muchas plantillas no lo configuran solas.",
    "recomendacion": "Añade la etiqueta que indica la dirección oficial de cada página. Suele resolverse con un plugin de SEO o desde la plantilla.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "pagina-noindex": {
    "id": "pagina-noindex",
    "categoria": "SEO",
    "titulo": "Tu página le está pidiendo a Google que no la muestre",
    "queSignifica": "Tu página tiene una instrucción que le dice a Google, literalmente, que no la incluya en sus resultados. Mientras siga ahí, por bien que esté todo lo demás, no aparecerás en las búsquedas.",
    "impacto": "Es uno de los problemas más graves de cara a Google: por bien que esté todo lo demás, esta página no aparecerá en los resultados mientras siga esa instrucción. Conviene revisarlo de inmediato.",
    "causa": "Muchas veces es un resto de cuando la web estaba en construcción y se olvidaron de quitar el bloqueo, o una casilla marcada por error.",
    "recomendacion": "Quita cuanto antes la instrucción que impide que Google indexe la página. Si la web ya está terminada, no debería estar ahí.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "critico",
    "confianza": "medido"
  },
  "sin-datos-estructurados": {
    "id": "sin-datos-estructurados",
    "categoria": "SEO",
    "titulo": "Google no recibe información extra sobre tu negocio",
    "queSignifica": "Hay una forma de darle a Google datos ordenados sobre tu negocio (que eres una empresa local, tu dirección, tus horarios, tus valoraciones o tus productos). Tu página no se los está enviando.",
    "impacto": "Sin esa información extra, Google entiende peor tu negocio y es más difícil que muestre detalles llamativos como las estrellas de valoración o el horario junto a tu resultado. Es una oportunidad de mejora, no un fallo grave.",
    "causa": "La mayoría de plantillas no lo incluyen por defecto; hay que añadirlo aparte.",
    "recomendacion": "Añade esta información ordenada según lo que sea tu web: ficha de empresa local con dirección y horario, productos, servicios o valoraciones. Suele hacerse con un plugin o a mano en la plantilla.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "sin-open-graph": {
    "id": "sin-open-graph",
    "categoria": "Conversión",
    "titulo": "Cuando comparten tu web en redes o WhatsApp, se ve sosa",
    "queSignifica": "Al pegar el enlace de tu web en WhatsApp, Facebook o LinkedIn, debería salir una tarjeta con imagen, título y descripción. Tu página no tiene esa información preparada, así que aparece un enlace pelado o con una imagen aleatoria.",
    "impacto": "Un enlace que se comparte sin imagen ni texto atractivo llama mucho menos la atención y puede recibir menos clics. Cuidarlo ayuda a que compartir tu web dé mejor impresión.",
    "causa": "Falta configurar los datos que usan las redes sociales para generar la vista previa.",
    "recomendacion": "Define para cada página una imagen, un título y una descripción para cuando se comparta. Suele resolverse con un plugin de SEO.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "imagenes-sin-alt": {
    "id": "imagenes-sin-alt",
    "categoria": "Accesibilidad",
    "titulo": "Tus imágenes no tienen una descripción de texto",
    "queSignifica": "Cada imagen puede llevar un texto que describe lo que muestra. Sirve para las personas que navegan con lectores de pantalla y también para que Google entienda la foto. Varias de tus imágenes no lo tienen.",
    "impacto": "Sin esa descripción, tus imágenes son invisibles para quienes usan lectores de pantalla y Google entiende peor qué muestran. Es una señal que conviene corregir por accesibilidad y por claridad.",
    "causa": "Es muy habitual: al subir fotos casi nadie rellena ese campo de descripción.",
    "recomendacion": "Añade a cada imagen relevante una descripción breve y natural de lo que se ve, por ejemplo 'Reforma de cocina moderna en blanco'. Se hace desde la galería de imágenes de tu web.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "contenido-escaso": {
    "id": "contenido-escaso",
    "categoria": "SEO",
    "titulo": "Tu página tiene muy poco contenido",
    "queSignifica": "La página tiene muy poco texto que explique de verdad lo que ofreces. Tanto a un visitante como a Google les cuesta entender bien de qué va y por qué deberían confiar en ti.",
    "impacto": "Una página con poco contenido puede transmitir menos confianza y darle a Google pocas razones para mostrarla. Ampliar y mejorar ese texto suele ser una de las acciones con más margen, aunque el resultado depende de cada web.",
    "causa": "Suele pasar en páginas hechas deprisa, con cuatro frases y alguna imagen, sin desarrollar los servicios.",
    "recomendacion": "Amplía el texto explicando tus servicios, resolviendo las dudas típicas de tus clientes y contando por qué elegirte. Escribe pensando en la persona, no en Google.",
    "dificultad": "Alta",
    "quien": "Tú mismo",
    "severidadMax": "importante",
    "confianza": "inferencia"
  },
  "sin-sitemap": {
    "id": "sin-sitemap",
    "categoria": "SEO",
    "titulo": "A tu web le falta el mapa que guía a Google por sus páginas",
    "queSignifica": "El mapa del sitio es una lista, pensada para Google, con todas las páginas de tu web. Ayuda a que las encuentre todas y no se deje ninguna. Tu web no lo tiene publicado.",
    "impacto": "Sin ese mapa, Google puede tardar más en descubrir algunas de tus páginas, sobre todo las nuevas o las más escondidas. Es una señal que conviene corregir, especialmente si tu web tiene muchas páginas.",
    "causa": "Falta generarlo o no se ha activado; muchos gestores lo crean con un plugin.",
    "recomendacion": "Genera y publica el mapa del sitio y avísale a Google de dónde está. Suele resolverse activando un plugin de SEO.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "sin-robots-txt": {
    "id": "sin-robots-txt",
    "categoria": "SEO",
    "titulo": "A tu web le falta el archivo que da indicaciones a Google",
    "queSignifica": "Es un pequeño archivo en la raíz de tu web que sirve para dar indicaciones a los buscadores: qué zonas pueden mirar y dónde está el mapa del sitio. El tuyo no existe.",
    "impacto": "No tenerlo no suele ser grave, pero es una pieza básica que conviene tener bien puesta para orientar a Google y evitar que pierda tiempo en zonas que no interesan. Es una mejora recomendable.",
    "causa": "Simplemente no se ha creado al montar la web.",
    "recomendacion": "Crea ese archivo con unas indicaciones básicas y la dirección de tu mapa del sitio. Es un ajuste rápido para quien lleve la parte técnica.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "propuesta-valor-poco-clara": {
    "id": "propuesta-valor-poco-clara",
    "categoria": "Conversión",
    "titulo": "No se entiende qué vendes en los primeros segundos",
    "queSignifica": "Cuando alguien entra en tu web, en los primeros segundos debería entender qué ofreces, a quién y por qué elegirte a ti. En tu página ese mensaje no aparece claro arriba del todo: hay que leer mucho o adivinarlo. Si el visitante no lo pilla rápido, se va antes de darte una oportunidad.",
    "impacto": "Una propuesta de valor confusa puede hacer que muchas visitas se marchen sin llegar a entender qué haces, aunque fueran clientes ideales. Es una señal que conviene revisar, porque suele ser lo primero que decide si alguien se queda o cierra la pestaña.",
    "causa": "Suele pasar cuando la portada arranca con un eslogan genérico ('Bienvenido', 'Calidad y confianza') en lugar de decir en cristiano qué haces y para quién. También ocurre cuando la web se hizo pensando en 'quedar bonita' y no en explicar el negocio.",
    "recomendacion": "Pon arriba del todo una frase corta y directa que diga qué ofreces, a quién y qué te diferencia (por ejemplo: 'Reformas de baño en Albacete, presupuesto en 24h'). Debajo, una segunda línea que la apoye. Que se entienda sin hacer scroll y sin conocimientos previos de tu sector.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "inferencia"
  },
  "sin-cta-claro": {
    "id": "sin-cta-claro",
    "categoria": "Conversión",
    "titulo": "No hay un botón claro que invite a dar el siguiente paso",
    "queSignifica": "Una web debe guiar al visitante hacia una acción concreta: pedir presupuesto, llamar, reservar o comprar. En tu página no se ve un botón evidente que diga qué hacer a continuación, o hay tantos elementos compitiendo que ninguno destaca. El visitante se queda sin saber cómo contactar contigo.",
    "impacto": "Sin una acción clara y visible, muchas personas interesadas pueden irse sin dar el paso, simplemente porque no encontraron el camino fácil. Es una de las señales que más conviene corregir, porque afecta directamente a que una visita se convierta en contacto.",
    "causa": "Ocurre cuando la web se centra en informar pero no en pedir la acción, o cuando el botón existe pero se pierde: mismo color que el fondo, texto vago ('Más información') o enterrado abajo del todo.",
    "recomendacion": "Coloca un botón principal bien visible, con un color que contraste y un texto que diga exactamente qué pasa al pulsarlo ('Pide presupuesto', 'Reserva tu cita'). Que aparezca arriba, sin tener que buscarlo, y repítelo a lo largo de la página en los momentos de decisión.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "inferencia"
  },
  "contacto-no-visible": {
    "id": "contacto-no-visible",
    "categoria": "Conversión",
    "titulo": "Cuesta encontrar cómo contactar contigo",
    "queSignifica": "Revisando tu web no se localizan de forma clara las vías de contacto: ni un teléfono visible, ni WhatsApp, ni un formulario evidente. Cuando alguien quiere darte trabajo y no ve rápido cómo hablar contigo, es muy fácil que desista y se vaya a la competencia.",
    "impacto": "Que el contacto no esté a la vista puede hacer que pierdas conversaciones con gente que ya estaba decidida. Es un punto crítico: por bueno que sea el resto de la web, si no encuentran cómo llegar a ti, no llegan.",
    "causa": "Suele deberse a que el contacto está solo en una página interna ('Contacto') a la que hay que navegar, o a que se dio por hecho que 'ya se ve' cuando en la práctica queda escondido en el pie o en un menú.",
    "recomendacion": "Deja el contacto siempre a mano: teléfono y/o WhatsApp visibles en la parte superior de todas las páginas, y un formulario corto fácil de encontrar. En móvil, un botón fijo de llamar o de WhatsApp ayuda mucho. La regla es que nadie tenga que buscar cómo hablar contigo.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "critico",
    "confianza": "inferencia"
  },
  "sin-prueba-social": {
    "id": "sin-prueba-social",
    "categoria": "Conversión",
    "titulo": "No se ven opiniones ni señales de que otros confían en ti",
    "queSignifica": "En tu web no aparecen reseñas, testimonios de clientes, valoraciones ni logos de marcas o colaboradores con los que trabajas. Esas señales son las que le dicen a un visitante nuevo 'esto va en serio y otros ya han confiado'. Sin ellas, tú dices que eres bueno, pero nadie lo respalda.",
    "impacto": "La falta de pruebas de que otros ya confían en ti puede hacer que un desconocido dude a la hora de dar el paso, sobre todo si tu servicio implica gastar dinero o dejar sus datos. Es una señal que conviene reforzar, porque la confianza pesa mucho en la decisión final.",
    "causa": "Pasa cuando el negocio tiene clientes contentos pero nunca ha recogido ni publicado sus opiniones, o cuando las reseñas están en Google pero no se muestran también en la propia web.",
    "recomendacion": "Recoge testimonios reales de clientes (nombre, foto o empresa si es posible) y muéstralos en la portada y en las páginas de servicio. Añade tus reseñas de Google si las tienes, y logos de clientes o certificaciones. Cuanto más concreto y verificable, más confianza transmite.",
    "dificultad": "Media",
    "quien": "Tú mismo",
    "severidadMax": "importante",
    "confianza": "inferencia"
  },
  "sin-redes-sociales": {
    "id": "sin-redes-sociales",
    "categoria": "Conversión",
    "titulo": "No hay enlaces a tus redes sociales",
    "queSignifica": "En tu web no se detectan enlaces a perfiles de redes sociales (Instagram, Facebook, LinkedIn, etc.). Para muchos visitantes, ver que tienes redes activas es una forma rápida de comprobar que el negocio existe de verdad, está vivo y hay gente detrás.",
    "impacto": "No enlazar tus redes puede hacer que pierdas una vía fácil de generar confianza y de que te sigan quienes aún no están listos para comprar. Es una mejora que suele sumar credibilidad, aunque no sea de las más urgentes.",
    "causa": "Ocurre cuando la web se montó sin incluir los iconos de redes, o cuando el negocio no tiene perfiles creados o los tiene abandonados y por eso no se enlazan.",
    "recomendacion": "Si tienes perfiles activos, añade sus iconos en la cabecera o el pie, enlazando a los perfiles reales. Si no los tienes, valora abrir al menos uno donde ya estén tus clientes y mantenlo con algo de actividad. Mejor ninguno que uno abandonado con la última publicación de hace años.",
    "dificultad": "Baja",
    "quien": "Tú mismo",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "telefono-no-clicable": {
    "id": "telefono-no-clicable",
    "categoria": "Conversión",
    "titulo": "Tu teléfono aparece, pero no se puede pulsar para llamar",
    "queSignifica": "Tienes el número de teléfono escrito en la web, pero está puesto como texto normal, no como un enlace de llamada. En el ordenador no se nota, pero desde el móvil significa que quien quiere llamarte tiene que memorizar el número o copiarlo a mano en lugar de tocar y llamar directamente.",
    "impacto": "Que el teléfono no sea pulsable puede hacer que pierdas llamadas de gente que iba a contactar desde el móvil y, ante el pequeño incordio de copiar el número, lo deja. Es un detalle técnico con efecto directo sobre cuántas personas terminan llamándote.",
    "causa": "Suele ser un despiste al montar la web: el número se escribió como texto sin convertirlo en enlace de llamada. Técnicamente es un cambio muy pequeño.",
    "recomendacion": "Convierte el número en un enlace de llamada (el clásico enlace 'tel:') para que en el móvil se pueda tocar y llamar al instante. Hazlo en todos los sitios donde aparezca el teléfono: cabecera, pie y página de contacto.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "contraste-bajo": {
    "id": "contraste-bajo",
    "categoria": "Accesibilidad",
    "titulo": "Hay texto que cuesta leer porque se confunde con el fondo",
    "queSignifica": "En tu web hay textos cuyo color es demasiado parecido al del fondo (por ejemplo, gris claro sobre blanco o texto encima de una foto). Cuesta leerlos, sobre todo desde el móvil, con sol o para personas con menos visión.",
    "impacto": "Puede hacer que parte de quienes te visitan lean con dificultad o directamente se salten información importante, como precios, condiciones o cómo contactar contigo.",
    "causa": "Suele venir de la paleta de colores de la marca o de plantillas que usan grises muy suaves, y de poner texto sobre imágenes sin una capa que lo destaque.",
    "recomendacion": "Ajusta los colores para que el texto destaque claramente sobre su fondo. Como referencia, el texto normal debería tener un contraste de al menos 4,5 a 1 respecto al fondo, un valor que se puede comprobar al momento antes de publicar.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "botones-sin-nombre": {
    "id": "botones-sin-nombre",
    "categoria": "Accesibilidad",
    "titulo": "Tienes botones que no explican para qué sirven",
    "queSignifica": "Algunos botones de tu web no tienen un nombre que los identifique (por ejemplo, un botón que es solo un icono, como una lupa o un carrito). Las personas que navegan con lector de pantalla no pueden saber qué hace ese botón.",
    "impacto": "Puede impedir que las personas que usan lector de pantalla completen acciones clave como buscar, enviar un formulario o comprar, porque no saben qué botón están pulsando.",
    "causa": "Es habitual en botones formados solo por un icono, a los que no se les ha añadido ni texto visible ni una etiqueta interna que los nombre.",
    "recomendacion": "Añade a cada botón un nombre claro: un texto visible o, si es solo un icono, una etiqueta interna (aria-label) que diga qué hace, por ejemplo 'Buscar' o 'Abrir menú'.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "enlaces-sin-nombre": {
    "id": "enlaces-sin-nombre",
    "categoria": "Accesibilidad",
    "titulo": "Tienes enlaces que no dicen a dónde llevan",
    "queSignifica": "Hay enlaces en tu web sin un texto que indique su destino (por ejemplo, iconos de redes sociales o imágenes enlazadas sin descripción). Con lector de pantalla suenan como 'enlace' a secas, sin más pista.",
    "impacto": "Puede dificultar la navegación a quien usa lector de pantalla y deja a todos con menos contexto sobre a dónde van al pulsar, lo que resta claridad a tu web.",
    "causa": "Suele pasar con enlaces hechos solo de un icono o una imagen a los que no se les ha puesto texto ni un texto alternativo que los describa.",
    "recomendacion": "Da a cada enlace un texto que describa su destino. Si es un icono o una imagen, añade un texto alternativo o una etiqueta interna, por ejemplo 'Ir a nuestro Instagram'.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "sin-idioma-declarado": {
    "id": "sin-idioma-declarado",
    "categoria": "Accesibilidad",
    "titulo": "Tu página no indica en qué idioma está escrita",
    "queSignifica": "A tu web le falta la marca que declara su idioma. Es un dato invisible para el visitante, pero los lectores de pantalla y los navegadores lo usan para saber que tu contenido está en español.",
    "impacto": "Puede provocar que los lectores de pantalla pronuncien mal tu contenido y que la traducción automática del navegador funcione peor, lo que empeora la experiencia de parte de tus visitantes.",
    "causa": "Casi siempre es una plantilla mal configurada a la que se le ha olvidado indicar el idioma de la página.",
    "recomendacion": "Declara el idioma de la página en su configuración (indicar que está en español, lang='es'). Es un cambio pequeño y de una sola vez.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "mejora",
    "confianza": "medido"
  },
  "campos-sin-etiqueta": {
    "id": "campos-sin-etiqueta",
    "categoria": "Accesibilidad",
    "titulo": "Hay campos de tus formularios sin una etiqueta que los identifique",
    "queSignifica": "En tus formularios hay casillas (nombre, email, teléfono) que no tienen una etiqueta asociada. A veces solo muestran un texto de ejemplo dentro que desaparece al empezar a escribir, y entonces ya no queda claro qué pedía cada casilla.",
    "impacto": "Puede provocar errores al rellenar el formulario y hacer más difícil que te contacten o compren, tanto para lectores de pantalla como para cualquiera que dude qué iba en cada campo.",
    "causa": "Es frecuente en formularios que usan solo el texto de ejemplo dentro del campo (placeholder) en lugar de una etiqueta fija visible.",
    "recomendacion": "Asocia a cada campo una etiqueta visible y estable que diga qué se pide, sin depender solo del texto de ejemplo interno.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "medido"
  },
  "zonas-tactiles-pequenas": {
    "id": "zonas-tactiles-pequenas",
    "categoria": "Accesibilidad",
    "titulo": "Algunos botones y enlaces son muy pequeños o están muy juntos para el móvil",
    "queSignifica": "Puede haber elementos que se pulsan (botones, enlaces del menú) demasiado pequeños o muy pegados entre sí. En el móvil, con el dedo, es fácil fallar el toque o pulsar el de al lado.",
    "impacto": "Puede frustrar a quien te visita desde el móvil y provocar toques erróneos justo cuando intenta llamarte, escribirte o comprar.",
    "causa": "Suele darse en menús con enlaces muy juntos, botones diminutos o iconos pegados que se diseñaron pensando más en el ordenador que en el móvil.",
    "recomendacion": "Da a los elementos que se pulsan un tamaño cómodo para el dedo (en torno a 48 píxeles) y deja separación suficiente entre ellos.",
    "dificultad": "Media",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "importante",
    "confianza": "inferencia"
  },
  "sin-viewport-movil": {
    "id": "sin-viewport-movil",
    "categoria": "Accesibilidad",
    "titulo": "Tu web no está preparada para verse bien en el móvil",
    "queSignifica": "A tu web le falta la instrucción que le dice al móvil cómo adaptar la página a su pantalla. Sin ella, se muestra como la versión de ordenador encogida y el visitante tiene que hacer zoom y mover la pantalla para leer.",
    "impacto": "Puede hacer que quienes entran desde el móvil tengan una experiencia difícil, y es una señal que conviene corregir porque Google se fija especialmente en cómo se ve tu web en el móvil.",
    "causa": "Falta la etiqueta de adaptación al móvil (meta viewport), algo habitual en webs antiguas o plantillas sin diseño adaptable.",
    "recomendacion": "Añade la instrucción de adaptación al móvil (meta viewport con width=device-width) y comprueba que el contenido se reordena bien en pantallas pequeñas.",
    "dificultad": "Baja",
    "quien": "Tu desarrollador / nosotros",
    "severidadMax": "critico",
    "confianza": "medido"
  }
};
